### ISSUE TITLE
Allow login with Google/OpenID

### ISSUE THREAD

**Issue by nazrhyn** [badhex/imud-issues#94]
Authenticate with Google or, better, support OpenID.

(shib)

**Comment by badhex** [comment]
This request has changed now that we're using amazon cognito. The framework to accept Google/Facebook IDs is there, but need to add support to the UI.

**Comment by badhex** [comment]
Implemented in: https://github.com/badhex/imud/commit/5c9c15532997d60132ab2feb7fa25b39dd94c545
